/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ys.test

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import ys.springboot.example.quartz.EnableYsQuartz

@EnableYsQuartz
@SpringBootApplication
class QuartzTestApplication

fun main(args: Array<String>) {
    runApplication<QuartzTestApplication>(*args)
}