/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ys.springboot.example

import org.junit.jupiter.api.Test


class HelloTest {
    @Test
    fun hello() {
        println("World!")
    }
}