/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ys.springboot.example

import kotlin.test.Test

class LibraryTest {
    @Test
    fun `default test code`() {
//        val classUnderTest = Application()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}